In [82]:
# f1 score use :


# Class imbalance: e.g., fraud detection, rare disease detection.

# When both False Positives and False Negatives are important.

# When you want a single number that balances
# the trade-off between precision and recall.


# It basically means that if we have Model 1 and Model 2,
# and both have same accuarcy then whom we choose ?

# we will choose the one with the higher F1 score —
# because it shows a better balance between precision and recall.

In [83]:
# example model 1

# accuracy  0.9
# precision 0.90
# recall    0.50
# f1        0.64

# vs
# accuracy  0.9
# precision 0.8
# recall    0.8
# f1        0.8

# Model 1: Precision is high, but recall is low → F1 score is moderate.

# Model 2: Precision and recall are balanced
# → F1 score is high → better choice.

In [84]:

import numpy as np
import pandas as pd

In [85]:

v = pd.read_csv("/content/heart.csv")

In [86]:

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(v.iloc[:,0:-1] ,
                                                       v.iloc[:,-1], test_size = 0.2 , random_state= 2)

In [87]:


from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [88]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [89]:

clf1.fit(x_train , y_train)
clf2.fit(x_train , y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [90]:

y_pred1 = clf1.predict(x_test)
y_pred2 = clf2.predict(x_test)

In [91]:

from sklearn.metrics import accuracy_score , confusion_matrix
print("Accuracy of Logistic regression" , accuracy_score(y_test , y_pred1)*100)
print("Accuracy of Decision Tree" , accuracy_score(y_test , y_pred2)*100)


Accuracy of Logistic regression 90.1639344262295
Accuracy of Decision Tree 85.24590163934425


**f1_score**

In [92]:

from sklearn.metrics import classification_report
print(classification_report(y_test , y_pred1))

              precision    recall  f1-score   support

           0       1.00      0.81      0.90        32
           1       0.83      1.00      0.91        29

    accuracy                           0.90        61
   macro avg       0.91      0.91      0.90        61
weighted avg       0.92      0.90      0.90        61



In [93]:
from sklearn.metrics import recall_score , precision_score , f1_score


In [94]:
print('for logistic regrression model ')
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test , y_pred1) , columns = list(range(0,2)))
print(cdf)
print("-"*50)
print("precision - " , precision_score(y_test , y_pred1)*100)
print("recall -" , recall_score(y_test , y_pred1)*100)
print("f1 score - " , f1_score(y_test , y_pred1)*100)

for logistic regrression model 
--------------------------------------------------
    0   1
0  26   6
1   0  29
--------------------------------------------------
precision -  82.85714285714286
recall - 100.0
f1 score -  90.625


In [95]:
print('for DT Model ')
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test , y_pred2) , columns = list(range(0,2)))
print(cdf)
print("-"*50)
print("precision - " , precision_score(y_test , y_pred2)*100)
print("recall -" , recall_score(y_test , y_pred2)*100)
print("f1 score - " , f1_score(y_test , y_pred2)*100)

for DT Model 
--------------------------------------------------
    0   1
0  25   7
1   2  27
--------------------------------------------------
precision -  79.41176470588235
recall - 93.10344827586206
f1 score -  85.71428571428571


In [96]:
# precision_score(y_test , y_pred1 , average = None)

# Class 0 precision = 1.0
# → Every time the model predicted "Class 0",
#  it was correct (no false positives).

# Class 1 precision = 0.82857143 (~82.86%)
# → Out of all times the model predicted "Class 1", 82.86% were correct,
#  and the rest were false positives.Class 0 precision = 1.0

# → Every time the model predicted "Class 0",
# it was correct (no false positives).

# Class 1 precision = 0.82857143 (~82.86%)
# → Out of all times the model predicted "Class 1", 82.86% were correct,
#  and the rest were false positives.

#  example
#         Your example’s case:

# Class 0: Precision = 1.0 → Whenever the model predicted Class 0,
#  it was always correct → no false positives.

# Class 1: Precision = 0.8285 → Means about 17% of the time
#  the model said “this is Class 1”,
#  it was actually wrong (false positives happened).

# important notes

#      we generally focus only at the postive side means our focus
#      has been at always the one side ...example
#      one got placement or not
#      one  have cancer or not
#      one  have diabetic or not

# more than 0 we lways like 1 ....
# but mathmatically our machine also calculates for 0 precsion
# not just for 1 precision

#              deep insight


# Exactly — we’re not just looking at the positive side (Class 1).

# When you set average=None in precision_score,

# Scikit-learn calculates precision separately for every class.

# That means it treats each class as the “positive class” once,
#  and calculates precision for it.

#     Example:
# If you have 2 classes → 0 and 1:

# Precision for Class 0:
# Treat Class 0 as “positive” and everything else as “negative.”
# Then measure precision.

# Precision for Class 1:
# Treat Class 1 as “positive” and everything else as “negative.”
# Then measure precision.

# So yes — you’re checking mistakes for every class separately,
# not just “positive side” in the binary sense.

# If you want, I can show you with a small table
# how scikit-learn flips perspective for each class.

# It’ll make this super clear.

In [97]:
precision_score(y_test , y_pred2 , average = None)

# for precision


array([0.92592593, 0.79411765])

In [98]:
recall_score(y_test , y_pred2 , average = None)

# for recall also we could see the accuracy for not just 1
# but for also 0 ...

# in binary class our focus genrally lies at only for yes , 1 etc
# but not at negative side
                        #      but what we have 3 classes
                        # then we must have to focus at all
                        # three classes ...



array([0.78125   , 0.93103448])

In [99]:
# class imbalance :

#    means some classes have way more samples
#    than others in your dataset..

# Example

# Say you’re building a model to detect if an email is spam or not:

# class          samples
# not spam (0)   9500
# spam  (1)       500

#  Why it’s a problem

# A dumb model that always predicts “Not Spam” will still be 95% accurate,
#  but it’s useless because it never catches spam.

# The model may get biased towards the majority
# class because it sees it more often during training.

In [100]:
#    micro pricision vs weighted precision

#  Micro Precision

# What it does:

# Counts total true positives and total false positives
# across all classes first, then applies the precision formula.

# Every prediction is weighted equally,
#  regardless of which class it belongs to.

# Basically: “Overall correctness of positive predictions,
# ignoring class imbalance.”


# When to use:


# When class imbalance doesn’t matter much.

# When you just care about overall model performance
# across all classes combined.

# Good for multi-class classification when you treat every instance equally.

In [101]:
# deep insight  if one class prediction is  100 true
# and other class precion is  0 percent false means predict all wrong
# then

# If only one class were important, then looking at per-class precision might not be necessary.
# But in the real world, every class has its own importance — and that’s where the problem comes in.

# Main problem — Model is a master on one side, but fails on the other

# Imagine you build an AI for a doctor that predicts two things:

# 0 = Healthy

# 1 = Cancer

# If your model always predicts “Healthy,” then:

# Precision for Healthy = 100%

# Precision for Cancer = 0%  (because it never detects it)

# The micro average might still be high because most patients are healthy.
# But does that mean the model is good?
# No — because the thing that was more important to detect (Cancer) has 0% performance.

# That’s why per-class precision is important:

# It shows you how well the model performs for each class.

# Otherwise, the performance of the big class will hide the failure
# on the small class.

# In business, healthcare, or fraud detection,
# missing the minority class can be a big risk.

# Simply put:

# It’s not enough to be correct for just one side.
# The model needs to be right for every class,
#  otherwise it’s like being half-blind.

In [102]:
# how we make it alright


# Yes, exactly — if Class 1 has 100% precision and Class 2 has 0%,
# that’s a problem,
# because it means the model is perfect for one class
# but completely useless for the other.

# How to fix this — Class imbalance & poor per-class performance

# 1. Balance the data

# Oversampling → Duplicate examples from the minority class (Class 2)
# or use algorithms like SMOTE.

# Undersampling → Remove some examples from the majority class (Class 1)
# so both classes have similar sizes.

# 2. Use class weights

# In training, set class_weight='balanced' (available in scikit-learn).

# This makes the model “punish” mistakes on the minority class more heavily.

# 3. Create better features

# Sometimes the model fails because the features don’t capture
# enough information for Class 2.

# Use feature engineering to make Class 2 patterns more distinct.

# 4. Algorithm tuning

# Adjust the decision threshold so the model detects more of Class 2.

# Try different algorithms (Random Forest, XGBoost, etc.)
# that handle imbalance better.

# Bottom line:

# You have to force the model to pay attention to the minority class (Class 2),
# otherwise it will always stay biased toward the majority class (Class 1).

# If you want, I can make a simple before/after example showing h
# ow adding class weights improves Class 2 precision.

In [103]:
# class weight

#            Class weight simply means:

# During training, you tell the model: “Mistakes on the minority
#  class should get a bigger penalty,
# and mistakes on the majority class should get a smaller penalty.”

#  Problem without class weight

# If your data has Class 0 = 90% and Class 1 = 10%,
# the model will focus more on Class 0 because there’s more data for it.
# Result: Class 1 gets ignored.

#  What class weight does

# When you set class_weight='balanced' (in scikit-learn),
# the algorithm assigns weights inversely proportional to class frequency:

# Formula:

# Weight for class
# =
# Total samples
# (Number of classes × Samples in that class)
# Weight for class=
# (Number of classes × Samples in that class)
# Total samples
# 	​


# Example:

# Class 0 (90 samples) → weight ≈ 0.56

# Class 1 (10 samples) → weight ≈ 5.0

# This means one wrong prediction for Class 1
# is punished about the same as nine wrong predictions for Class 0.

#  Benefit

# The model takes both classes more seriously.

# Precision and recall for the minority class can improve significantly.

# If you want, I can show you a small before/after example
# where adding class weights boosts Class 1 precision .

In [104]:
v1 = pd.read_csv("/content/mnist.csv")

In [105]:
v1.head(5)

# there are  10 classes between 0 to 9


label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [106]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(v1.iloc[:,1:],v1.iloc[:,0],test_size=0.2,random_state=2)

In [107]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [108]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [109]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [110]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [111]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9145238095238095
Accuracy of Decision Trees 0.8511904761904762


In [112]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix



0    1    2    3    4    5    6    7    8    9
0  791    0    1    0    1    9   11    1    6    1
1    0  938    2    4    0    3    0    3   12    0
2    2    9  745   16    9    4   13   13   15    3
3    1    4   19  763    0   36    5    5   20   11
4    2    5    4    0  804    1    7    3    9   21
5    9    3    4   23   10  610   15   10   34   11
6   12    4   12    1    7    8  789    0    5    1
7    3    2   13    6    4    2    0  812    2   29
8   11   12   13   18    1   21    6    6  694   11
9    3    6    2   14   25    4    0   37    7  736

In [113]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix



0    1    2    3    4    5    6    7    8    9
0  748    1   12    9    3   17   13    4   13    1
1    0  900   10   11    8    6    4    4   16    3
2   12   18  663   34   18   15   16   22   25    6
3    7    9   28  698    6   42    9   15   27   23
4    8    6   11    9  734   13    7    6   22   40
5   13   11   11   35   13  572   27   10   23   14
6   12    1   11    4   11   21  757    1   16    5
7    3    8   22   15    7    5    1  785    9   18
8    9   15   27   36   22   28   13    7  611   25
9    7    6   10   19   47   16    3   25   19  682

In [114]:

from sklearn.metrics import precision_score,recall_score,f1_score

In [120]:
precision_score(y_test,y_pred1,average= None)

# we could see the precision for every class

array([0.94844125, 0.95422177, 0.91411043, 0.90295858, 0.93379791,
       0.8739255 , 0.93262411, 0.91235955, 0.86318408, 0.89320388])

In [121]:
recall_score(y_test,y_pred1,average= None)

array([0.9634592 , 0.97505198, 0.8986731 , 0.88310185, 0.93925234,
       0.83676269, 0.94040524, 0.930126  , 0.87515763, 0.882494  ])

In [122]:
precision_score(y_test,y_pred1,average= None)

array([0.94844125, 0.95422177, 0.91411043, 0.90295858, 0.93379791,
       0.8739255 , 0.93262411, 0.91235955, 0.86318408, 0.89320388])

In [123]:
precision_score(y_test,y_pred1,average= "macro")

0.9128827064397905

In [124]:
recall_score(y_test,y_pred1,average= "macro")

0.9124484028871509

In [115]:
precision_score(y_test,y_pred1,average='weighted')
# go to hard notes for better understanding

0.9142150713630827

In [116]:
recall_score(y_test,y_pred1,average='weighted')

0.9145238095238095

In [126]:
f1_score(y_test,y_pred1,average='macro')

0.9125721045561427

In [117]:
f1_score(y_test,y_pred1,average='weighted')

0.9142794994052751

In [118]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       821
           1       0.95      0.98      0.96       962
           2       0.91      0.90      0.91       829
           3       0.90      0.88      0.89       864
           4       0.93      0.94      0.94       856
           5       0.87      0.84      0.85       729
           6       0.93      0.94      0.94       839
           7       0.91      0.93      0.92       873
           8       0.86      0.88      0.87       793
           9       0.89      0.88      0.89       834

    accuracy                           0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400

