(column transformer )class of Scikit-learn

use :se-case of ColumnTransformer:
Suppose you have:

Some categorical columns → need OneHotEncoder

Some numerical columns → need StandardScaler

You can apply both in one shot using ColumnTransformer.

In [198]:
import numpy as np
import pandas as pd

In [199]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

##   from sklearn.impute import SimpleImputer
 Use: To fill in (impute) missing values in your dataset.

 ##  from sklearn.preprocessing import OneHotEncoder
 Use: To convert categorical values into one-hot vectors (i.e., binary format: 0/1 columns for each category).

##  from sklearn.preprocessing import OrdinalEncoder
 Use: To convert categorical values into integer labels (1st category = 0, 2nd = 1, etc.).

In [200]:
 v = pd.read_csv('covid_toy.csv')

In [201]:
v.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [202]:
v['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [203]:
v.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

could say that fever has 10 missing values

In [204]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(v.drop(columns=['has_covid']),v['has_covid'],
                                                test_size=0.2)

........here we drop the coulumn of has covid from x or from input but selected has column for output or for y .........

**AAm Zindagi**

In [205]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

 Creates an object si from

 **SimpleImputer**.

By default, it will fill missing values (NaN) with the mean of the column.

1)
**X_train_fever = si.fit_transform(X_train[['fever']])**
This does two things:

**.fit(...)**→ Computes the mean (or strategy) of the 'fever' column in training data.

.**transform(...)** → Replaces NaN in 'fever' column with that computed mean.

So:
Missing values in training data are filled based on the training set's own 'fever' values.



In [206]:
X_train_fever

array([[104.        ],
       [100.        ],
       [100.        ],
       [ 98.        ],
       [ 99.        ],
       [102.        ],
       [104.        ],
       [ 98.        ],
       [103.        ],
       [102.        ],
       [ 98.        ],
       [103.        ],
       [103.        ],
       [102.        ],
       [ 98.        ],
       [101.        ],
       [100.95833333],
       [100.        ],
       [ 98.        ],
       [100.95833333],
       [100.        ],
       [100.        ],
       [101.        ],
       [ 98.        ],
       [103.        ],
       [ 99.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [101.        ],
       [102.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [ 99.        ],
       [104.        ],
       [100.95833333],
       [101.        ],
       [104

 simple imputer filled missing values in fewer  by the mean of values ....

In [207]:
X_train_fever.shape

(80, 1)

In [208]:
# ordinalencoding - cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

In [209]:
X_train_cough

array([[0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],

In [216]:
X_train_cough.shape

(80, 1)

In [219]:
#one hot encoding gender , city

ohe = OneHotEncoder(drop='first', sparse_output=False)
x_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
# alsa test the data
x_test_gender_city = ohe.fit_transform(X_test[['gender','city']])
x_train_gender_city



array([[0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],


In [215]:
 x_train_gender_city

array([[0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],


In [229]:
# extraction age
X_train_age = X_train.drop(columns=['gender', 'fever', 'cough', 'city']).values


# also the dtest data
X_test_age = X_test.drop(columns=['gender', 'fever', 'cough', 'city']).values
#
X_train_age


array([[18],
       [27],
       [19],
       [80],
       [59],
       [69],
       [12],
       [12],
       [69],
       [24],
       [73],
       [16],
       [73],
       [74],
       [34],
       [38],
       [20],
       [80],
       [40],
       [38],
       [11],
       [19],
       [ 8],
       [65],
       [60],
       [22],
       [10],
       [34],
       [47],
       [42],
       [65],
       [26],
       [19],
       [49],
       [64],
       [81],
       [64],
       [16],
       [15],
       [72],
       [56],
       [79],
       [14],
       [54],
       [51],
       [65],
       [51],
       [71],
       [69],
       [50],
       [11],
       [14],
       [60],
       [71],
       [82],
       [19],
       [83],
       [55],
       [10],
       [34],
       [51],
       [65],
       [23],
       [17],
       [13],
       [42],
       [66],
       [42],
       [75],
       [48],
       [34],
       [31],
       [46],
       [ 5],
       [83],
       [64],
       [44],

   we call np.concantenate to add age , fever ,gender city ,cough

In [234]:

x_train_transformed = np.concatenate((x_train_gender_city,X_train_age,X_train_fever,X_train_cough),axis=1)
# also the test data
x_test_transformed = np.concatenate((X_test_age ,x_test_gender_city,X_test_age,X_test_fever,X_test_cough),axis=1)
X_train_age.shape


(80, 1)

**Mentos Zindagi**

.........in this what is happening is that .......this below class  will tranform all cloumn  strings into number in just  few syntax .... at above cases we are applying diffrent diffrent logic to make string into number ...and it was was quite tough......

In [240]:
from sklearn.compose import ColumnTransformer

In [246]:
transformer = ColumnTransformer(transformers = [
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output = False,drop='first'),['gender','city'])
] , remainder = 'passthrough')

In [247]:
transformer.fit_transform(X_train)

array([[104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  18.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  19.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  80.        ],
       [ 99.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  59.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  69.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.    

In [249]:
transformer.fit_transform(X_train).shape

(80, 7)

In [255]:
transformer.transform(X_test).shape

(20, 7)