In [79]:
## missing indicator ...means making separate column  of missing ...
## example we have column of age  ..35   and fare is 32 then
## missing column which is suppose named as age_na will be filled by false
## also
## if age = na and fare = 35 ...then missing column ...that is named as age_na
## will be filed as T


# actually few participants used this technique to make thier model
 # more accurate ..nad hence it worked and they won  the  Competition....


# by this we are adding missing indicator .... our model learn to identify
# the row of missing and non missing........


In [80]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import SimpleImputer, MissingIndicator



# simple imputer

# Part of scikit-learn.

# Used to fill missing values in your dataset.

# Works for numerical or categorical data
#  (depending on strategy you choose).



## MissingIndicator

# This adds extra columns (binary) that indicate
# whether a value was missing in the original data.

# Useful because missingness can be informative for the model.



In [81]:
v = pd.read_csv('/content/train (2).csv' , usecols= ['Age','Fare','Survived'])

In [82]:
v.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [83]:
x = v.drop(columns=['Survived'])
y = v['Survived']

In [84]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [85]:
x_train.head()

Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

In [86]:
si = SimpleImputer()

#   simple imputer()

# It is a tool from scikit-learn that can replace NaN values in your dataset
# with some calculated value.

# By default:
# It looks for missing values (NaN).
# It fills them with the mean of that column.

                # si

      # si = SimpleImputer()
#  This line creates an object called si
#  which is responsible for filling missing values in your data.


x_train_trf = si.fit_transform(x_train)

# here fit actually means learning the  data and making the formula to replace
# the missing values and tranform are  means to apply the formula to replace
# the missing values ....# so we replace all missing value by the mean value to both train set  and
# testing test too....
# so we replace all missing value by the mean value to both train set  and
# testing test too....

x_test_trf = si.transform(x_test)

# now we take the mean value from train data  set and from that
# mean value we will fill the  mising values too ...
# mean value is stored in si .....its more likely  we study in oops
# now we transform the column of test by the ttrain meean value
# we did not applied  fit in  x test because  we dont have to
#  make my modfel lkearn and derive the faormula or to find out the mean
# value
         # because......

  # If you calculate a new mean or mode from the test data,
  # you cause data leakage (information from the test set
                       #   indirectly gets into model training).
# In the real world, the test data is unseen,
# so you must transform it using only the statistics
# learned from the training data



In [87]:
print("Imputation values learned from train:", si.statistics_)
print("Column order:", x_train.columns.tolist())

# this syntax is taken from chatgpt just to
# getting ....to know the mean value .....

Imputation values learned from train: [29.78590426 32.28905604]
Column order: ['Age', 'Fare']


In [88]:

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf , y_train)

y_pred = clf.predict(x_test_trf)


In [89]:

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

61.452513966480446

so here what we are doing is to finding out the accuarcy without using missing
indicator ....so we got of accuacy 61 ....now we going to see our accuracy by
planting the feature of missing indicator ....

In [90]:
mi  = MissingIndicator()
# missing indicator is a scikit learn class ...
# herre mi is making a object to generate of column for
# missing value

mi.fit(x_train)
# so basically it learns at which column there is missing value
# or to scan the missing value ...



MissingIndicator()

In [91]:
mi.features_

# actually this is the  scikit learn function will return 0 and stored 0
# wherever the missing values this  finds out......

array([0])

In [92]:
x_train_missing = mi.transform(x_train)

# so here we are making  missing indicator ("separate column") for our x train
# data which will give the true false for missing no missing

In [93]:
x_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [94]:
x_test_missing = mi.transform(x_test)

In [95]:
x_test_missing

# mi.transform(x_train) returns a NumPy array
#  (or sparse matrix), not a pandas DataFrame.
# This is because scikit-learn transformers by default work
# with NumPy arrays—they are not pandas-aware unless you explicitly wrap them.

# Output shape: (n_samples, n_features_selected)

# Each column represents a feature
# (an indicator for a missing column),
# but it's in array format, not DataFrame.



array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [102]:
x_train['Age_NA'] = x_train_missing


In [108]:
x_train

Age      Fare  Age_NA
30   40.0   27.7208   False
10    4.0   16.7000   False
873  47.0    9.0000   False
182   9.0   31.3875   False
876  20.0    9.8458   False
..    ...       ...     ...
534  30.0    8.6625   False
584   NaN    8.7125    True
493  71.0   49.5042   False
527   NaN  221.7792    True
168   NaN   25.9250    True

[712 rows x 3 columns]

In [109]:
x_test['Age_NA'] = x_test_missing

In [110]:
x_test

Age     Fare  Age_NA
707  42.0  26.2875   False
37   21.0   8.0500   False
615  24.0  65.0000   False
169  28.0  56.4958   False
68   17.0   7.9250   False
..    ...      ...     ...
89   24.0   8.0500   False
80   22.0   9.0000   False
846   NaN  69.5500    True
870  26.0   7.8958   False
251  29.0  10.4625   False

[179 rows x 3 columns]

In [115]:
si = SimpleImputer()

x_train_trf2 = si.fit_transform(x_train)
# here x_train_trf2 ::  it is just variable using to store and
# to understand by the
# name that what we are doing here .....

# si.fit
x_test_trf2 = si.transform(x_test)

##                         # reason
#                   why  we did missing indicator
#                    as well as simple imputer too


# If you only impute (fill with mean),
#  the model never knows which values were originally missing.

# Adding MissingIndicator creates extra binary features
# that preserve this information, which can improve accuracy in some cases.

# Then, SimpleImputer fills actual missing values
# so the model can work without NaNs.

# This is a standard practice in machine learning → it gives the model both:
# the filled value (so algorithms don’t break)
#  the missingness signal (which can be important for prediction)



In [116]:
x_train_trf2

array([[ 40.        ,  27.7208    ,   0.        ],
       [  4.        ,  16.7       ,   0.        ],
       [ 47.        ,   9.        ,   0.        ],
       ...,
       [ 71.        ,  49.5042    ,   0.        ],
       [ 29.78590426, 221.7792    ,   1.        ],
       [ 29.78590426,  25.925     ,   1.        ]])

In [125]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf2 , y_train)

y_pred = clf.predict(x_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

63.128491620111724

In [121]:
                     # shortcut for  making missing indicator
            # as well as for simple imputing

si = SimpleImputer(add_indicator=True)

In [122]:
x_train = si.fit_transform(x_train)
x_test = si.fit_transform(x_test)

In [123]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf2 , y_train)

y_pred = clf.predict(x_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

63.128491620111724

**GRID SEARCH CV**